version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
  mysql:
    image: mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/data/postgres
    ports:
      - "3306:3306"
    networks:
      - db
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - db
  redis:
    image: bitnami/redis
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: password
    volumes:
      - redis:/bitnami
    networks:
      - db
networks:
  db:
    driver: bridge

volumes:
  postgres:
  mysql:
  mongo:
  redis: